application/task/models.py
from application import db

class Task(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    date_created = db.Column(db.DateTime, default=db.func.current_timestamp())
    date_modified = db.Column(db.DateTime, default=db.func.current_timestamp(),
    onupdate=db.func.current_timestamp())

    owner_id = db.Column(db.Integer, db.ForeignKey('account.id'), nullable=False)

    taskname = db.Column(db.String(144), nullable=False)
    description = db.Column(db.String(2000))
    important = db.Column(db.Boolean, nullable=False)
    taskdone = db.Column(db.Boolean, nullable=False)

    def __init__(self, taskname, description, owner_id):
        self.taskname = taskname
        self.description = description
        self.owner_id = owner_id
        self.important = False
        self.taskdone = False

application/user/models.py
from flask_login import UserMixin
from application import db

class User(db.Model, UserMixin):
    __tablename__ = "account"

    id = db.Column(db.Integer, primary_key=True)
    date_created = db.Column(db.DateTime, default=db.func.current_timestamp())
    date_modified = db.Column(db.DateTime, default=db.func.current_timestamp(),
    onupdate=db.func.current_timestamp())

    tasks = db.relationship('Task', order_by='desc(Task.important)', backref='account', lazy=True)

    username = db.Column(db.String(144), nullable=False, unique=True)
    email = db.Column(db.String(144), nullable=False, unique=True)
    password = db.Column(db.String(144), nullable=False)
    admin = db.Column(db.Boolean, nullable=False)
    deleted = db.Column(db.Boolean, nullable=False)

    def __init__(self, username, email, password):
        self.username = username
        self.email = email
        self.password = password
        self.admin = False
        self.deleted = False

application/task/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField
from wtforms.validators import DataRequired, Length

class TaskForm(FlaskForm):
    taskname = StringField('Task name', validators=[DataRequired(), Length(min=3, max=140)])
    description = TextAreaField('Description', validators=[Length(max=1900)])

application/user/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, EmailField
from wtforms.validators import DataRequired, Email, Length, EqualTo

class RegisterForm(FlaskForm):
    username = StringField('User name', validators=[DataRequired(),
                                Length(min=3, max=140)])
    email = EmailField('Email address', validators=[DataRequired(),
                                Email(), Length(min=3, max=140)])
    password = PasswordField('Password', validators=[DataRequired(),
                            Length(min=3, max=140), EqualTo('password_confirm',
                                                    message='passwords do not match')])
    password_confirm = PasswordField('Password again', validators=[DataRequired(),
                                                        Length(min=3, max=140)])

application/__init__.py
from flask import Flask

app = Flask(__name__)

app.config.from_prefixed_env()
if app.config['ENV'] == 'development':
    app.config.from_object('application.config-dev')
elif app.config['ENV'] == 'testing':
    app.config.from_object('application.config-test')
else:
    app.config.from_object('application.config')

from application.db import db, migrate, db_upgrade
from application.auth import login_manager, register_emptyform
from application.views import main_page
from application.auth.views import auth_bp
from application.user.views import user_bp
from application.task.views import task_bp

db.init_app(app)
migrate.init_app(app, db)

login_manager.init_app(app)
register_emptyform(app)

app.register_blueprint(main_page)
app.register_blueprint(auth_bp)
app.register_blueprint(user_bp)
app.register_blueprint(task_bp)

db_upgrade(app)

application/task/views.py
from flask import Blueprint, redirect, render_template, request, flash, url_for
from flask_login import login_required, current_user
from flask_wtf import FlaskForm

from application import db
from application.task.forms import TaskForm
from application.task.models import Task

task_bp = Blueprint('task', __name__)

@task_bp.get('/tasks')
@login_required
def list_tasks():
    return render_template("task/list_tasks.html")

@task_bp.route('/tasks/add', methods=['GET', 'POST'])
@login_required
def create_task():
    form = TaskForm(request.form)
    if form.validate_on_submit():
        task = Task(form.taskname.data, form.description.data,
                    current_user.id)
        db.session.add(task)
        db.session.commit()
        flash('Task added!', 'success')
        return redirect(url_for('task.list_tasks'))
    return render_template("task/add_task.html", form = form)

@task_bp.get('/tasks/<int:task_id>')
@login_required
def show_task(task_id):
    task = Task.query.get(task_id)
    if not task or task.owner_id != current_user.id:
        return redirect(url_for('task.list_tasks'))
    return render_template("task/single_task.html", task=task)

@task_bp.post('/tasks/<int:task_id>/done')
@login_required
def task_done(task_id):
    form = FlaskForm(request.form)
    task = Task.query.get(task_id)
    if not task or task.owner_id != current_user.id:
        return redirect(url_for('task.list_tasks'))
    if form.validate_on_submit():
        task.taskdone = not task.taskdone
        db.session.commit()
    return redirect(url_for('task.show_task', task_id=task_id))

@task_bp.post('/tasks/<int:task_id>/important')
@login_required
def task_important(task_id):
    form = FlaskForm(request.form)
    task = Task.query.get(task_id)
    if not task or task.owner_id != current_user.id:
        return redirect(url_for('task.list_tasks'))
    if form.validate_on_submit():
        task.important = not task.important
        db.session.commit()
    return redirect(url_for('task.show_task', task_id=task_id))

application/user/views.py
from flask import Blueprint, redirect, render_template, request, flash, url_for
from werkzeug.security import generate_password_hash
from flask_login import login_required

from application import db
from application.user.forms import RegisterForm
from application.user.models import User

user_bp = Blueprint('user', __name__)

@user_bp.route('/register', methods=['GET', 'POST'])
def register():
    form = RegisterForm(request.form)
    if form.validate_on_submit():
        try:
            user = User(form.username.data, form.email.data,
                        generate_password_hash(form.password.data))
            db.session.add(user)
            db.session.commit()
            flash('Registration successful!', 'success')
            return redirect(url_for('index.index'))
        except:
            flash('account name or email already in use', 'danger')
            return render_template("user/register.html", form = form)
    return render_template("user/register.html", form = form)

@user_bp.get('/account')
@login_required
def account():
    return render_template("user/account.html")

application/views.py
from flask import Blueprint, render_template

main_page = Blueprint('index', __name__, template_folder='templates')

@main_page.route('/')
def index():
    return render_template('index.html')

application/templates/index.html
{% extends "layout.html" %}

{% block body %}
  <p>
    Hello world!
  </p>
  {% if current_user.is_authenticated %}
  <p>
    Hi {{ current_user.username }}!
  </p>
  {% endif %}
{% endblock %}

application/templates/layout.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>TodoApp</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" 
      rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" 
      crossorigin="anonymous">
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="/">TodoApp</a>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <div class="navbar-nav me-auto mb-2 mb-lg-0">
            <a class="nav-link active" href="/">Home</a>
            <a class="nav-link" href="/tasks">Tasks</a>
          </div>
          <div class="navbar-nav mb-2 mb-lg-0">
          {% if not current_user.is_authenticated %}
              <a class="nav-link" href="/register">Register</a>
              <a class="nav-link" href="/login">Login</a>
          {% else %}
            <a class="nav-link" href="/account">{{ current_user.username }}</a>
            <form method="POST" action="{{ url_for('auth.logout') }}">
              {{ emptyform.csrf_token }}
              <input class="nav-link nav-item border-0 bg-light" type="submit" value="Logout"/>
            </form>
          {% endif %}
          </div>
        </div>
      </div>
    </nav>
    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
      {% for category, message in messages %}
      <div class="alert alert-{{ category }}" role="alert">
        {{ message }}
      </div>
      {% endfor %}
    {% endif %}
  {% endwith %}
    {% block body %}
      <p>
        Content.
      </p>
    {% endblock %}
  </body>
</html>

application/templates/task/add_task.html
{% extends "layout.html" %}

{% block body %}
    <form method="POST" action="{{ url_for('task.create_task') }}">
        {{ form.csrf_token }}
        <table>
            <tr>
                <td>
                    {{ form.taskname.label }}
                </td>
                <td>
                    {{ form.taskname }}
                </td>
                {% if form.taskname.errors %}
                <td>
                <ul class="alert alert-danger" role="alert">
                    {% for error in form.taskname.errors %}
                    <li>{{ error }}</li>
                    {% endfor %}
                </ul>
                </td>
                {% endif %}
            </tr>
            <tr>
                <td>
                    {{ form.description.label }}
                </td>
                <td>
                    {{ form.description }}
                </td>
                {% if form.description.errors %}
                <td>
                <ul class="alert alert-danger" role="alert">
                    {% for error in form.description.errors %}
                    <li>{{ error }}</li>
                    {% endfor %}
                </ul>
                </td>
                {% endif %}
            </tr>
            <tr>
                <td colspan="2">
                    <input class="btn btn-primary" type="submit" value="Add task"/>
                </td>
            </tr>
    </form>
{% endblock %}

application/templates/task/list_tasks.html
{% extends "layout.html" %}

{% block body %}
<div>
    <h1>Tasks</h1>
    <a class="btn btn-primary" href="/tasks/add" role="button">Add new task</a>
    <h2>Active tasks</h2>
    {% for task in current_user.tasks %}
    {% if not task.taskdone %}
        <div><a href="/tasks/{{task.id}}">{{ task.taskname }}</a></div>
    {% endif %}
    {% endfor %}
    <h2>Done</h2>
    {% for task in current_user.tasks %}
    {% if task.taskdone %}
        <div><a href="/tasks/{{task.id}}">{{ task.taskname }}</a></div>
    {% endif %}
    {% endfor %}
</div>
{% endblock %}

application/templates/task/single_task.html
{% extends "layout.html" %}

{% block body %}
<div>
    <h1>{{ task.taskname }}</h1>
    {% if task.important %}
    <div class="btn btn-danger btn-sm">Important</div>
    {% endif %}
    {% if task.taskdone %}
    <div class="btn btn-success btn-sm">Done</div>
    {% endif %}
    <div>{{ task.description }}</div>
    <div>
        <form method="POST" action="{{ url_for('task.task_important', task_id=task.id) }}">
            {{ emptyform.csrf_token }}
            {% if task.important %}
            <input class="btn btn-primary" type="submit" value="Mark unimportant"/>
            {% else %}
            <input class="btn btn-primary" type="submit" value="Mark important"/>
            {% endif %}
        </form>
    </div>
    <div>
        <form method="POST" action="{{ url_for('task.task_done', task_id=task.id) }}">
            {{ emptyform.csrf_token }}
            {% if task.taskdone %}
            <input class="btn btn-primary" type="submit" value="Mark undone"/>
            {% else %}
            <input class="btn btn-primary" type="submit" value="Mark done"/>
            {% endif %}
        </form>
    </div>
</div>
{% endblock %}

application/templates/user/account.html
{% extends "layout.html" %}

{% block body %}
    <div>
        <h1>{{ current_user.username }}</h1>
        <p>{{ current_user.email }}</p>
    </div>
{% endblock %}

application/templates/user/register.html
{% extends "layout.html" %}

{% block body %}
    <form method="POST" action="{{ url_for('user.register') }}">
        {{ form.csrf_token }}
        <table>
            <tr>
                <td>
                    {{ form.username.label }}
                </td>
                <td>
                    {{ form.username }}
                </td>
                {% if form.username.errors %}
                <td>
                <ul class="alert alert-danger" role="alert">
                    {% for error in form.username.errors %}
                    <li>{{ error }}</li>
                    {% endfor %}
                </ul>
                </td>
                {% endif %}
            </tr>
            <tr>
                <td>
                    {{ form.email.label }}
                </td>
                <td>
                    {{ form.email }}
                </td>
                {% if form.email.errors %}
                <td>
                <ul class="alert alert-danger" role="alert">
                    {% for error in form.email.errors %}
                    <li>{{ error }}</li>
                    {% endfor %}
                </ul>
                </td>
                {% endif %}
            </tr>
            <tr>
                <td>
                    {{ form.password.label }}
                </td>
                <td>
                    {{ form.password }}
                </td>
                {% if form.password.errors %}
                <td>
                <ul class="alert alert-danger" role="alert">
                    {% for error in form.password.errors %}
                    <li>{{ error }}</li>
                    {% endfor %}
                </ul>
                </td>
                {% endif %}
            </tr>
            <tr>
                <td>
                    {{ form.password_confirm.label }}
                </td>
                <td>
                    {{ form.password_confirm }}
                </td>
                {% if form.password_confirm.errors %}
                <td>
                <ul class="alert alert-danger" role="alert">
                    {% for error in form.password_confirm.errors %}
                    <li>{{ error }}</li>
                    {% endfor %}
                </ul>
                </td>
                {% endif %}
            </tr>
            <tr>
                <td colspan="2">
                    <input class="btn btn-primary" type="submit" value="Register"/>
                </td>
            </tr>
    </form>
{% endblock %}